trigger: 
  batch: true
  branches:
    include:
      - master
pool:
    vmImage: 'windows-latest'

jobs:
    - job: SQL
      displayName: "Connect SQL" 
      steps:
        - task: AzureCLI@2
          displayName: Azure CLI
          inputs:
            azureSubscription: "test-svc-con"
            scriptType: "bash"
            scriptLocation: inlineScript
            inlineScript: |
              az --version
              az account show
              az account set -s "dd37ffa9-fa1b-45e7-b351-0085043d774a"
              Current_IP=$(curl ipinfo.io/ip)
              echo $Current_IP
              az sql server firewall-rule create --resource-group "msi-poc" --server "msi-poc-sql-svr" -n "BAIPRange" --start-ip-address $Current_IP --end-ip-address $Current_IP
              echo "added build agent IP to the sql firewall"
              
        - bash: |
            echo "trying to connect to sql"
            sqlcmd -?
            sqlcmd -G
            nslookup "msi-poc-sql-svr.database.windows.net"
            Sqlcmd -Smsi-poc-sql-svr.database.windows.net -dNotes -U "john@naushadalamoutlook.onmicrosoft.com" -P "***" -G -Q "select * from notes"
            echo "Login completed"
